# Probability and statistics

In [1]:
import numpy as np

In this exercise we will apply basic concepts of probability and statistics to help a robot localise itself. Robot localization is an important task for any mobile robot as it needs to know where in the world it is currently situated in.

You may think robot localization is a very easy problem as you can use GPS. But no! GPS has errors in localization upto a few metres which is very inaccurate for self driving cars.

Hence, the robot needs to use sensors to locate itself. And sensors are noisy! Even the motion of a robot is uncertain.

For the purposes of this exercise, let us assume that the world is a one dimensional world with  N  grid cells. Each grid cell is colored either red or green which can be measured using a sensor located in the robot. However, the sensor measurements are noisy and hence we need to take a probabilitic approach to determine in which of these grid cells the robot is situated in at a given instant of time.

image

The robot can move either left or right in this cyclic world. This motion is uncertain as well prompting us again to take a probabilistic approach. For example you may instruct the robot to move  5  cells. But it may move  4/6  cells due to a wheel slip.

When the robot is switched on, it is in a state of maximum confusion. It doesn't know where it is situated. We will model this state of maximum confusion as uniform distribution. In other words, the robot has equal belief of being present in any of the cells.

Complete the below function to return an array where the  ith  array element is the probability that the robot is in the  ith  grid cell at time instant  0  when the robot is switched on.

In [2]:
# Modify the empty list, p, so that it becomes a UNIFORM probability
# distribution over n grid cells, as expressed in a list of 
# n probabilities.
def init_distribution(n):
    p = np.ones((5))
    # Add your code here
    p *= 1/n
    
    # End your code here
    return p.tolist()

In [3]:
init_distribution(5)

[0.2, 0.2, 0.2, 0.2, 0.2]

In [9]:
#given P(g|r) = .25, P(r|r) = .75
#Modify the code below so that the function sense, which 
#takes p and Z as inputs, will output the normalized 
#probability distribution, q, after multiplying the entries 
# in p according to the color in the corresponding cell in world,
# followed by normalization of the probability values
world=['green', 'red', 'red', 'green', 'green']
p = [0.2, 0.2, 0.2, 0.2, 0.2]

def sense(p, Z):
    q = np.zeros((len(p)))
    # Add your code here
    for i in range(len(p)):
        if world[i] !=Z:
            q[i] = 0.25*p[i]
        else:
            q[i] = 0.75*p[i]
    q /= np.sum(q)  
    # End your code here
    return q.tolist()
            
sense(p, 'red')

[0.11111111111111112,
 0.33333333333333337,
 0.33333333333333337,
 0.11111111111111112,
 0.11111111111111112]

In [10]:
#Modify the code so that it updates the probability twice
#and gives the posterior distribution after both 
#measurements are incorporated. Make sure that your code 
#allows for any sequence of measurement of any length.

# DO NOT MODIFY THE SENSE FUNCTION. JUST CALL THE SENSE FUNCTION APPROPRIATELY

p=[0.2, 0.2, 0.2, 0.2, 0.2]
world=['green', 'red', 'red', 'green', 'green']
measurements = ['red', 'green']

# Add your code here
for i in measurements:
    p = sense(p,i)   
# End your code here
print(p)

[0.19999999999999998, 0.19999999999999998, 0.19999999999999998, 0.19999999999999998, 0.19999999999999998]


In [11]:
#Program a function that returns a new distribution 
#q, shifted to the right by U units. If U=0, q should 
#be the same as p.

def move(p, U):
    q = np.zeros(len(p))
    p = np.array(p)
    # ADD CODE HERE
    if(U==0):
        return p
    else:
        q = np.roll(p,U)
    # END CODE HERE
    return q

move([0.11, 0.33, 0.33, 0.11, 0.11], 1)

array([0.11, 0.11, 0.33, 0.33, 0.11])

In [16]:
#Modify the move function to accommodate the added 
#probabilities of overshooting or undershooting 
#the intended destination.

def move(p,U):
    
    q = np.zeros(len(p))
    for i in range(len(p)):
        q[i] = 0.1*p[(i+1-U)%5] + 0.8*p[(i-U)%5] + 0.1*p[(i-U-1)%5]
    return q
    
move([0, 1.0, 0,0,0],1)

array([0. , 0.1, 0.8, 0.1, 0. ])

In [18]:
# Write code that makes the robot move twice and then prints 
# out the resulting distribution, starting with the initial 
# distribution p = [0, 1, 0, 0, 0]

# Call the function appropriately from here

# ADD CODE HERE
move(move([0, 1.0, 0, 0, 0], 1), 1)
# END CODE HERE


array([0.01, 0.01, 0.16, 0.66, 0.16])

In [19]:
#write code that moves 1000 times and then prints the 
#resulting probability distribution.

p = [0, 1, 0, 0, 0]
# ADD CODE HERE
for i in range(1000):
    q = move(p,1)
    p = q
# END CODE HERE
p

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [20]:
#Given the list motions=[1,1] which means the robot 
#moves right and then right again, compute the posterior 
#distribution if the robot first senses red, then moves 
#right one, then senses green, then moves right again, 
#starting with a uniform prior distribution.

world=['green', 'red', 'red', 'green', 'green']
measurements = ['red', 'green']
motions = [1,1]

p = init_distribution(len(world))
# ADD CODE HERE
for i in range(2):
    q = sense(p, measurements[i])
    print(q)
    q1 = move(q, motions[i])
    print(q1)
    p = q1
print(p)


[0.11111111111111112, 0.33333333333333337, 0.33333333333333337, 0.11111111111111112, 0.11111111111111112]
[0.11111111 0.13333333 0.31111111 0.31111111 0.13333333]
[0.15789473684210525, 0.06315789473684211, 0.14736842105263157, 0.4421052631578947, 0.18947368421052632]
[0.21157895 0.15157895 0.08105263 0.16842105 0.38736842]
[0.21157895 0.15157895 0.08105263 0.16842105 0.38736842]
